apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api
  labels:
    app: simple-bank-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 # allow 2 extra pods during update
      maxUnavailable: 0 # never take a pod down before new one is ready
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
        - name: simple-bank-api
          image: ghcr.io/xavier-tame/simple-bank:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
