name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=raw,value=latest

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: Generate app.env from Doppler
        run: doppler secrets download --no-file --format env-no-quotes > app.env
        env:
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PROD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - uses: actions/checkout@v5

      - name: Set up kubectl
        uses: azure/setup-kubectl@v5

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode > /tmp/ca.crt
          kubectl config set-cluster simple-bank \
            --server="${{ secrets.KUBE_SERVER }}" \
            --certificate-authority=/tmp/ca.crt

          kubectl config set-credentials github-actions-deployer \
            --token="${{ secrets.KUBE_TOKEN }}"

          kubectl config set-context deploy-context \
            --cluster=simple-bank \
            --user=github-actions-deployer \

          kubectl config use-context deploy-context

      - name: Apply all K8s manifests
        run: kubectl apply -f k8s/ --validate=false

      - name: Update image to SHA tag
        run: |
          kubectl set image deployment/simple-bank-api \
            simple-bank-api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:sha-${{ github.sha }}

      - name: Force image pull (rollout restart)
        run: kubectl rollout restart deployment/simple-bank-api

      - name: Wait for rollout to complete
        run: kubectl rollout status deployment/simple-bank-api --timeout=120s
